#!/bin/bash

## Description: Installs Drupal and configures for DruxtSite.
## Usage: drupal-install
## Example: "ddev drupal-install"

# Install composer dependencies.
composer install

# Install Drupal with Tome.
drush -y tome:install

# Generate keys for Simple OAuth.
# drush simple-oauth:generate-keys ../keys

